// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGmDnfalrbNHEaPJHjRuO-sbk_4TA2Nqw',
    appId: '1:361457586588:web:362ecc540ec7dc2890f859',
    messagingSenderId: '361457586588',
    projectId: 'smart-school-b0764',
    authDomain: 'smart-school-b0764.firebaseapp.com',
    storageBucket: 'smart-school-b0764.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBphhiEew9AOoLN2eFl2zFZAh6JmSXxrxY',
    appId: '1:361457586588:android:36589a30661cd95290f859',
    messagingSenderId: '361457586588',
    projectId: 'smart-school-b0764',
    storageBucket: 'smart-school-b0764.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP-hUf0wIxoYyPLNkZv3vx6Fxr3wtTIAg',
    appId: '1:361457586588:ios:a3fa707569cf1b0790f859',
    messagingSenderId: '361457586588',
    projectId: 'smart-school-b0764',
    storageBucket: 'smart-school-b0764.firebasestorage.app',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP-hUf0wIxoYyPLNkZv3vx6Fxr3wtTIAg',
    appId: '1:361457586588:ios:a3fa707569cf1b0790f859',
    messagingSenderId: '361457586588',
    projectId: 'smart-school-b0764',
    storageBucket: 'smart-school-b0764.firebasestorage.app',
    iosBundleId: 'com.example.smartSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGmDnfalrbNHEaPJHjRuO-sbk_4TA2Nqw',
    appId: '1:361457586588:web:ad933d73df73ff4190f859',
    messagingSenderId: '361457586588',
    projectId: 'smart-school-b0764',
    authDomain: 'smart-school-b0764.firebaseapp.com',
    storageBucket: 'smart-school-b0764.firebasestorage.app',
  );
}
